<?php
/**
 * Created by PhpStorm.
 * User: kibb
 * Date: 4/14/18
 * Time: 7:59 AM
 */

namespace App\Auto;
use Illuminate\Database\Eloquent\Model;

class Student extends Model{
    protected $fillable = [
        'name',
        'matric_number',
        'department',
        'result'
        ];
    public function setConnection($name)
    {
        return parent::setConnection($name); // TODO: Change the autogenerated stub
    }

    public function bootIfNotBooted()
    {
        parent::bootIfNotBooted();
    }
}